empty --regenerate-exemptions

diff --git a/.github/workflows/supply-chain.yml b/.github/workflows/supply-chain.yml
--- a/.github/workflows/supply-chain.yml
+++ b/.github/workflows/supply-chain.yml
@@ -75,32 +75,51 @@ jobs:
         run: echo "${{ runner.tool_cache }}/cargo-vet/bin" >> $GITHUB_PATH
       - name: Ensure that the tool cache is populated with the cargo-vet binary
         run: cargo install --root ${{ runner.tool_cache }}/cargo-vet cargo-vet
-      - name: Check if last commit was by Dependabot
+      - name: Check which event triggered this CI run, a push or a pull request.
         run: |
-          git fetch origin ${{ github.head_ref }}
-          git switch ${{ github.head_ref }}
           EVENT_NAME="${{ github.event_name }}"
+          IS_PR="false"
+          IS_PUSH="false"
           if [[ "$EVENT_NAME" == "pull_request" ]]; then
             echo "This CI run was triggered in the context of a pull request."
-            SHA="${{ github.event.pull_request.head.sha }}"
+            IS_PR="true"
           elif [[ "$EVENT_NAME" == "push" ]]; then
             echo "This CI run was triggered in the context of a push."
-            SHA="${{ github.sha }}"
+            IS_PUSH="true"
           else
             echo "ERROR: This CI run was not triggered in the context of a pull request or a push. Exiting with error."
             exit 1
           fi
-          COMMIT_AUTHOR=$(gh api repos/${{ github.repository }}/commits/$SHA --jq .author.login)
+          echo "IS_PR=$IS_PR" >> $GITHUB_ENV
+          echo "IS_PUSH=$IS_PUSH" >> $GITHUB_ENV
+      - name: Check if last commit was by Dependabot
+        run: |
+          git fetch origin ${{ github.head_ref }} # ensure that we are up to date.
+          git switch ${{ github.head_ref }} # ensure that we are NOT in a detached HEAD state. This is important for the commit action in the end.
+
+          # Depending on the trigger for, the relevant commit has to be deduced differently.
+          if [[ "$IS_PR" == true ]]; then
+            # This is the commit ID for the last commit to the head branch of the pull request.
+            # If we used github.sha here instead, it would point to a merge commit between the PR and the main branch, which is only created for the CI run.
+            SHA="${{ github.event.pull_request.head.sha }}"
+          elif [[ "$IS_PUSH" == "true" ]]; then
+            SHA="${{ github.sha }}" # This is the last commit to the branch.
+          else
+            echo "ERROR: This action only supports pull requests and push events as triggers. Exiting with error."
+            exit 1
+          fi
           echo "Commit SHA is $SHA"
-          echo "author is $COMMIT_AUTHOR"
+
+          COMMIT_AUTHOR=$(gh api repos/${{ github.repository }}/commits/$SHA --jq .commit.author.name)
+          echo "The author of the last commit is $COMMIT_AUTHOR"
           if [[ "$COMMIT_AUTHOR" == "dependabot[bot]" ]]; then
             echo "The last commit was made by dependabot"
-            IS_DEPENDABOT=true
+            LAST_COMMIT_IS_BY_DEPENDABOT=true
           else
             echo "The last commit was made by $COMMIT_AUTHOR not by dependabot"
-            IS_DEPENDABOT=false
+            LAST_COMMIT_IS_BY_DEPENDABOT=false
           fi
-          echo "IS_DEPENDABOT=$IS_DEPENDABOT" >> $GITHUB_ENV
+          echo "LAST_COMMIT_IS_BY_DEPENDABOT=$LAST_COMMIT_IS_BY_DEPENDABOT" >> $GITHUB_ENV
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - name: Check if the last commit's message ends in "--regenerate-exemptions"
@@ -115,14 +134,23 @@ jobs:
             REGEN_EXEMP=false
           fi
           echo "REGEN_EXEMP=$REGEN_EXEMP" >> $GITHUB_ENV
-      - name: Regenerate vet exemptions for dependabot PRs
-        if: github.actor == 'dependabot[bot]' && (env.IS_DEPENDABOT == 'true' || env.REGEN_EXEMP=='true')   # Run only for Dependabot PRs or if specifically requested
+      - name: Check if the CI run happens in the context of a dependabot PR # Even if a PR is created by dependabot, the last commit can, and often should be, the regeneration of the cargo vet exemptions. It could also be from an individual making manual changes.
+        run: |
+          IN_DEPENDABOT_PR_CONTEXT="false"
+          if [[ $IS_PR == "true" ]]; then
+            if [[ "${{ github.event.pull_request.user.login }}" == "dependabot[bot]" ]]; then
+              IN_DEPENDABOT_PR_CONTEXT="true"
+            fi
+          fi
+          echo "IN_DEPENDABOT_PR_CONTEXT=$IN_DEPENDABOT_PR_CONTEXT" >> $GITHUB_ENV
+      - name: Regenerate cargo vet exemptions if we are in the context of a PR created by dependabot and the last commit is by dependabot or a regeneration of cargo vet exemptions was explicitly requested.
+        if: env.IN_DEPENDABOT_PR_CONTEXT == 'true' && (env.LAST_COMMIT_IS_BY_DEPENDABOT == 'true' || env.REGEN_EXEMP=='true')   # Run only for Dependabot PRs or if specifically requested
         run: cargo vet regenerate exemptions
-      - name: Check for changes in case of dependabot PR
-        if: github.actor == 'dependabot[bot]' && (env.IS_DEPENDABOT == 'true' || env.REGEN_EXEMP=='true') # Run only for Dependabot PRs or if specifically requested
+      - name: Check for changes if we are in the context of a PR created by dependabot and the last commit is by dependabot or a regeneration of cargo vet exemptions was explicitly requested.
+        if: env.IN_DEPENDABOT_PR_CONTEXT == 'true' && (env.LAST_COMMIT_IS_BY_DEPENDABOT == 'true' || env.REGEN_EXEMP=='true') # Run only for Dependabot PRs or if specifically requested
         run: git diff --exit-code || echo "Changes detected, committing..."
-      - name: Commit and push changes for dependabot PRs
-        if: success() && github.actor == 'dependabot[bot]' && (env.IS_DEPENDABOT == 'true' || env.REGEN_EXEMP=='true')
+      - name: Commit and push changes if we are in the context of a PR created by dependabot and the last commit is by dependabot or a regeneration of cargo vet exemptions was explicitly requested.
+        if: success() && env.IN_DEPENDABOT_PR_CONTEXT == 'true' && (env.LAST_COMMIT_IS_BY_DEPENDABOT == 'true' || env.REGEN_EXEMP=='true')
         uses: stefanzweifel/git-auto-commit-action@v6
         with:
           commit_message: Regenerate cargo vet exemptions
